name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: List files in the root directory
      run: ls -alh

    - name: Check if requirements.txt exists
      id: check_requirements
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt does not exist in the root directory."
          echo "REQUIREMENTS_EXISTS=false" >> $GITHUB_ENV
        else
          echo "REQUIREMENTS_EXISTS=true" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      if: env.REQUIREMENTS_EXISTS == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      if: env.REQUIREMENTS_EXISTS == 'true'
      run: |
        python -m unittest discover -s tests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Check if requirements.txt exists (for deployment)
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt does not exist in the root directory for deployment."
          exit 1
        fi

    - name: Install dependencies (for deployment)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      run: |
        echo "Deploying to production"
