name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      requirements_exists: ${{ steps.check_requirements.outputs.exists }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: List files in the root directory
      run: ls -alh

    - name: Check if requirements.txt exists
      id: check_requirements
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt does not exist in the root directory."
          echo "::set-output name=exists::false"
        else
          echo "::set-output name=exists::true"
        fi

    - name: Install dependencies
      if: steps.check_requirements.outputs.exists == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      if: steps.check_requirements.outputs.exists == 'true'
      run: |
        python -m unittest discover -s tests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.outputs.requirements_exists == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies (for deployment)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      run: |
        echo "Deploying to production"
